
# 註解
### 發出需求的分隔線

GET http://localhost:3001/try-qs?a=1&b=2


### 分隔線

POST http://localhost:3001/try-post
Content-Type: application/x-www-form-urlencoded

name=小吉&age=12

### 分隔線

POST http://localhost:3001/try-post
Content-Type: application/json

{ 
    "name": "烏薩奇", 
    "email": "rabbit@example.com", 
    "message": "這是⼀個測試訊息" 
} 
